apiVersion: v1
kind: Service
metadata:
  name: transaction-manager-server-node-port-service
  labels:
    name: transaction-manager-server-node-port-service
  namespace: default
spec:
  type: NodePort
  selector:
    name: transaction-manager-server-pod
  ports:
    - port: 8080
      targetPort: 8080
