apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster-service
  labels:
    name: mysql-cluster-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    name: mysql-pod
  ports:
    - port: 3306
      targetPort: 3306