apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # Here put the password of root user of the mysql server, encoded in base 64.
  password: _________________
